### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by mhulse** [davidwinter/wordpress-with-git#5]
Just out of curiosity, do you have any tips on how to handle WP's new auto update feature with this type of Git setup?

See http://make.wordpress.org/core/2013/10/25/the-definitive-guide-to-disabling-auto-updates-in-wordpress-3-7/.

I think the optimal workflow would be to allow for minor updates and then use Git to pull the major ones.

What's your thoughts on this topic?

**Comment by nathangross** [comment]
I shot @davidwinter a [tweet](https://twitter.com/nathangross/status/394897059201155072) about this the other day. Would love to get his input here, but I think auto updates are disabled on a git/svn deployed install.

Recently read this:

[There are a couple of other methods developers should know about:](http://wpmu.org/how-to-turn-off-automatic-updates-in-wordpress-3-7/)

*If you’re using a deployment system that uses SVN or GIT it’s disabled by default

*You can also make use of the auto_upgrader_disabled automatic_updater_disabled OR auto_upgrade_core auto_update_core filters

**Comment by nathangross** [comment]
Sorry, @mhulse I just now actually read the article you linked up... what I wrote was already covered :)

**Comment by mhulse** [comment]
> Sorry, @mhulse I just now actually read the article you linked up... what I wrote was already covered :)

No worries at all!

> I shot @davidwinter a tweet about this the other day. Would love to get his input here, but I think auto updates are disabled on a git/svn deployed install.

Yah, that's the info I've uncovered as well (the articles we link to cover this).

Here's what I'd like to do:
1. A submodule Workflow like how this repo is setup.
2. Allow minor updates (based on techniques described in articles).
3. Manual submodule updates of large version bumps.

My concern is, if I allowed minor updates to happen, wouldn't that cause merge conflicts down the road when I go to upgrade the WP submodule to major releases?

I'm wondering what happens when one goes to upgrade a submodule that been allowed to do minor, non-git, updates? Again, will there be merge/update conflicts?

@nathangross, what's your plans for handling this (i.e., submodules WP with auto updates)?

Thanks for the help/reply! Glad to know I'm not the only one wondering about this type of thing. :octocat:

**Comment by davidwinter** [comment]
Easiest option is to just disable the updates in `wp-config.php` and to continue doing what you've been doing previously. In my case, I have setup a Rake task to update versions and commit for me:

```
desc 'Update Wordpress'
task :wordpress_update, :version do |t, args|
  puts args[:version]
  commands = [
    'git pull',
    'cd public/wordpress',
    'git checkout master',
    'git fetch --tags',
    "git checkout #{args[:version]}",
    'cd ../..',
    'git add public/wordpress',
    "git commit -m 'Update Wordpress to #{args[:version]}'",
    'git push',
  ]

  system commands.join(' && ')
end
```

I then run this with:

```
rake wordpress_update[3.7]
```

If you want to enable and use the automatic upgrades, then it seems you'll have to do a few things.

Depending on your webserver, you'll need to grant write permissions so that the webserver can overwrite the files for you. From my previous experience, this has never been a good thing to do. I'd be interested in reading more on this again to see what current opinion is.

Also, if you allow for minor upgrades to be applied automatically, then that'll make the Wordpress sub-repository dirty - uncommitted changes will be in there. And if I remember rightly, that'll mean you couldn't update that sub-repository without either committing the changes (which we don't want to do) or cleaning the directory back to the original checked out state then pulling down a new tag/version of Wordpress.

If we can clean and pull down a tag in one command, that'll probably be the direction to go.

**Comment by mhulse** [comment]
@davidwinter Thanks so much for the reply and details! I really appreciate it.

> Easiest option is to just disable the updates in `wp-config.php` and to continue doing what you've been doing previously.

I like easy. My daily/weekly/monthly workflow (not just WordPress) is already complicated enough.

> In my case, I have setup a Rake task to update versions and commit for me:

Interesting! I have not played much with Ruby. I'll have to experiment with your example code. Thanks for sharing!

> Also, if you allow for minor upgrades to be applied automatically, then that'll make the Wordpress sub-repository dirty - uncommitted changes will be in there. And if I remember rightly, that'll mean you couldn't update that sub-repository without either committing the changes (which we don't want to do) or cleaning the directory back to the original checked out state then pulling down a new tag/version of Wordpress.
> 
> If we can clean and pull down a tag in one command, that'll probably be the direction to go.

Thanks for details, I totally agree with your last line.

I'll do some research and post back here if I learn anything useful.

At the very minimum, I plan on continuing my manual updates like always (as you stated above). If I can get the auto update to work for minor things, and make it easy to update the submodule as a one (or two) liner, then I'd like to head down that path.

Thanks again for the help!
